[modem]
porta_simulador = COM11
porta_windows   = COM10
baud_rate       = 115200
velocidade      = 56000

[rede]
servidor_ip = 10.99.99.1
cliente_ip  = 10.99.99.2
dns         = 8.8.8.8

[seguranca]
max_tentativas    = 3
bloqueio_segundos = 60
timeout_sessao    = 3600
max_sessoes       = 1

[usuarios]
; formato: nome = senha
; adicione ou remova linhas a vontade
discador = 1234
